repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        args:
          [
            --disallow-untyped-defs,
            --no-implicit-optional,
            --warn-unused-ignores,
            --warn-redundant-casts,
            --warn-unreachable,
          ]
        exclude: test
        additional_dependencies: [types-requests, xarray]
