name: tests-coverage

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.rst'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch
    - name: Set up Earth Engine
      env:
        EE_TOKEN: ${{ secrets.EE_TOKEN }}
      run: |
        mkdir -p /home/runner/.config/earthengine
        echo "$EE_TOKEN" > /home/runner/.config/earthengine/credentials
    - name: Test with pytest
      run: |
        hatch run test:coverage --cov-report=xml
    - name: Upload to Codecov
      run: |
        bash <(curl -s https://codecov.io/bash)
    - uses: actions/upload-artifact@v2
      with:
        path: coverage.xml
